apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: localhost:5432
    database: saju_naming
    user: saju_user
    secureJsonData:
      password: "saju2024!"
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true