// This file should be generated by Supabase CLI
// For now, we'll create a basic type structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          phone: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      saju_data: {
        Row: {
          id: string
          user_id: string
          name: string
          birth_date: string
          birth_time: string
          is_lunar: boolean
          gender: string
          year_gan: string
          year_ji: string
          month_gan: string
          month_ji: string
          day_gan: string
          day_ji: string
          hour_gan: string
          hour_ji: string
          wood_count: number
          fire_count: number
          earth_count: number
          metal_count: number
          water_count: number
          primary_yongsin: string | null
          secondary_yongsin: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          birth_date: string
          birth_time: string
          is_lunar?: boolean
          gender: string
          year_gan: string
          year_ji: string
          month_gan: string
          month_ji: string
          day_gan: string
          day_ji: string
          hour_gan: string
          hour_ji: string
          wood_count: number
          fire_count: number
          earth_count: number
          metal_count: number
          water_count: number
          primary_yongsin?: string | null
          secondary_yongsin?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          birth_date?: string
          birth_time?: string
          is_lunar?: boolean
          gender?: string
          year_gan?: string
          year_ji?: string
          month_gan?: string
          month_ji?: string
          day_gan?: string
          day_ji?: string
          hour_gan?: string
          hour_ji?: string
          wood_count?: number
          fire_count?: number
          earth_count?: number
          metal_count?: number
          water_count?: number
          primary_yongsin?: string | null
          secondary_yongsin?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      naming_results: {
        Row: {
          id: string
          user_id: string
          saju_data_id: string
          last_name: string
          first_name: string
          full_name: string
          last_name_hanja: string | null
          first_name_hanja: string | null
          total_strokes: number
          balance_score: number
          sound_score: number
          meaning_score: number
          overall_score: number
          generation_method: string
          ai_model: string | null
          ai_prompt: string | null
          preferred_values: Json | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          saju_data_id: string
          last_name: string
          first_name: string
          full_name: string
          last_name_hanja?: string | null
          first_name_hanja?: string | null
          total_strokes: number
          balance_score: number
          sound_score: number
          meaning_score: number
          overall_score: number
          generation_method: string
          ai_model?: string | null
          ai_prompt?: string | null
          preferred_values?: Json | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          saju_data_id?: string
          last_name?: string
          first_name?: string
          full_name?: string
          last_name_hanja?: string | null
          first_name_hanja?: string | null
          total_strokes?: number
          balance_score?: number
          sound_score?: number
          meaning_score?: number
          overall_score?: number
          generation_method?: string
          ai_model?: string | null
          ai_prompt?: string | null
          preferred_values?: Json | null
          notes?: string | null
          created_at?: string
        }
      }
      favorites: {
        Row: {
          id: string
          user_id: string
          naming_result_id: string
          rating: number | null
          comment: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          naming_result_id: string
          rating?: number | null
          comment?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          naming_result_id?: string
          rating?: number | null
          comment?: string | null
          created_at?: string
        }
      }
      hanja_dict: {
        Row: {
          id: string
          character: string
          meaning: string
          korean_reading: string
          chinese_reading: string | null
          strokes: number
          radical: string | null
          element: string
          usage_frequency: number
          name_frequency: number
          category: string[]
          gender: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          character: string
          meaning: string
          korean_reading: string
          chinese_reading?: string | null
          strokes: number
          radical?: string | null
          element: string
          usage_frequency?: number
          name_frequency?: number
          category?: string[]
          gender?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          character?: string
          meaning?: string
          korean_reading?: string
          chinese_reading?: string | null
          strokes?: number
          radical?: string | null
          element?: string
          usage_frequency?: number
          name_frequency?: number
          category?: string[]
          gender?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_sessions: {
        Row: {
          id: string
          user_id: string
          token: string
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          token: string
          expires_at: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          token?: string
          expires_at?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}